version: "3"

services:
  app:
    container_name: thesaurus-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8081:8081"
    networks:
      - backend

  database:
    container_name: mongo
    image: mongo
    networks:
      - backend

networks:
  backend:
