version: "3"

services:
  app:
    container_name: thesaurus
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: thesaurus-mongo
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

networks:
  backend:

volumes:
  mongo:
