version: '3'

services:
  app:
    container_name: thesaurus-server
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend

  database:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

networks:
  backend:

volumes:
  mongo:
