version: "3"

services:
  app:
    container_name: thesaurus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend

  database:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - backend

networks:
  backend:
