version: "3"

services:
  app:
    container_name: thesaurus-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8081:8081"
    restart: always
    networks:
      - backend

  database:
    image: mongo:latest
    container_name: mongo
    restart: always
    networks:
      - backend
    volumes:
      - mongo:/data/db

networks:
  backend:

volumes:
  mongo:
